INSERT INTO PASSENGER (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES ('1', 'firstName', 'lastName', 'email');
INSERT INTO PASSENGER (ID, FIRST_NAME, LAST_NAME, EMAIL) VALUES ('2', 'firstName1', 'lastName1', 'email1');

INSERT INTO FLIGHT (ID, DEPARTURE, ARRIVAL, DEPARTURE_DATE, ARRIVAL_DATE) VALUES ('1', 'departure1', 'arrival1', 'departureDate1', 'arrivalDate1');
INSERT INTO FLIGHT (ID, DEPARTURE, ARRIVAL, DEPARTURE_DATE, ARRIVAL_DATE) VALUES ('2', 'departure2', 'arrival2', 'departureDate2', 'arrivalDate2');

INSERT INTO BOOKING (ID, PASSENGER_ID, FLIGHT_ID) VALUES ('1', '1', '1');
INSERT INTO BOOKING (ID, PASSENGER_ID, FLIGHT_ID) VALUES ('2', '1', '2');